name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Build
      # TODO: Split these into separate lines.
      run: sudo apt update && sudo apt install -y cmake && cmake -S . -B build && cmake --build build
